import { type DomainResult } from '../errors/result.ts';
import type { IntegrityHash } from '../portfolio/evidence.ts';
import type { ActorId, ApprovalId, EvidenceId, IdempotencyKey, PortfolioId, RebalanceRunId, ExecutionRunId } from '../shared/identifiers.ts';
import type { PortfolioStateVersion } from '../shared/state-version.ts';
import type { Instant } from '../shared/time.ts';
import { type ApprovalBinding, type ApprovalState } from './contracts.ts';
export type DecisionKind = 'APPROVE_BASKET' | 'APPROVE_SUBSET' | 'REJECT';
export type ApprovalDecisionSnapshot = Readonly<{
    approvalId: ApprovalId;
    portfolioId: PortfolioId;
    rebalanceRunId: RebalanceRunId;
    state: ApprovalState;
    decisionKind: DecisionKind;
    binding?: ApprovalBinding;
    reasonCode?: string;
    decidedBy: ActorId;
    authorizationEvidenceId: EvidenceId;
    mfaEvidenceId?: EvidenceId;
    idempotencyKey: IdempotencyKey;
    decisionHash: IntegrityHash;
    decidedAt: Instant;
    stateVersion: number;
    consumedByExecutionRunId?: ExecutionRunId;
}>;
export declare function isTerminalApprovalState(state: ApprovalState): boolean;
export declare function isActiveApprovalState(state: ApprovalState): boolean;
export declare function isApprovalConsumable(snapshot: ApprovalDecisionSnapshot): boolean;
export declare function isApprovalExpired(snapshot: ApprovalDecisionSnapshot, nowInstant: Instant): boolean;
export declare function approveBasket(snapshot: ApprovalDecisionSnapshot, binding: ApprovalBinding, allProposedKeys: readonly IntegrityHash[], decisionHash: IntegrityHash, nextVersion: number): DomainResult<ApprovalDecisionSnapshot>;
export declare function approveSubset(snapshot: ApprovalDecisionSnapshot, binding: ApprovalBinding, allProposedKeys: readonly IntegrityHash[], mandatoryKeys: readonly IntegrityHash[], decisionHash: IntegrityHash, nextVersion: number): DomainResult<ApprovalDecisionSnapshot>;
export declare function rejectApproval(snapshot: ApprovalDecisionSnapshot, reasonCode: string, decisionHash: IntegrityHash, nextVersion: number): DomainResult<ApprovalDecisionSnapshot>;
export declare function invalidateApproval(snapshot: ApprovalDecisionSnapshot, nextVersion: number): DomainResult<ApprovalDecisionSnapshot>;
export declare function expireApproval(snapshot: ApprovalDecisionSnapshot, nextVersion: number): DomainResult<ApprovalDecisionSnapshot>;
export declare function consumeApproval(snapshot: ApprovalDecisionSnapshot, executionRunId: ExecutionRunId, nextVersion: number): DomainResult<ApprovalDecisionSnapshot>;
export declare function requiresApprovalReadyPlan(planState: string): DomainResult<void>;
export declare function verifyApprovalBinding(snapshot: ApprovalDecisionSnapshot, currentPlanHash: IntegrityHash, currentPortfolioVersion: PortfolioStateVersion, nowInstant?: Instant, executionRunId?: ExecutionRunId): DomainResult<void>;
