import { type DomainFailureCode } from '../errors/failure.ts';
import { type DomainResult } from '../errors/result.ts';
import type { IntegrityHash } from '../portfolio/evidence.ts';
import type { CancellationId, ExecutionRunId, IdempotencyKey, InstrumentId, OrderId, PortfolioId, ResidualWorkId } from '../shared/identifiers.ts';
import type { Money } from '../shared/money.ts';
import type { Quantity } from '../shared/quantity.ts';
import type { Instant } from '../shared/time.ts';
import { type BrokerOrderReference, type BrokerSide, type DeliveryProduct, type NormalizedFill, type OrderIntentPayload, type OrderState, type SubmissionAttempt, type SubmissionCertainty } from './contracts.ts';
import type { AccountingDelta } from './fill-accounting.ts';
export type CancellationOutcome = 'ACKNOWLEDGED' | 'REJECTED' | 'UNKNOWN';
export type CancellationAttemptRecord = Readonly<{
    cancellationId: CancellationId;
    orderId: OrderId;
    idempotencyKey: IdempotencyKey;
    requestedBy: string;
    reasonCode: string;
    requestedAt: Instant;
    deadlineAt: Instant;
}>;
export type CancellationOutcomeRecord = Readonly<{
    cancellationId: CancellationId;
    outcome: CancellationOutcome;
    completedAt: Instant;
    brokerAsOf?: Instant;
    failureCode?: DomainFailureCode;
}>;
export type ExecutionOrderSnapshot = Readonly<{
    orderId: OrderId;
    executionRunId: ExecutionRunId;
    portfolioId: PortfolioId;
    instrumentId: InstrumentId;
    side: BrokerSide;
    product: DeliveryProduct;
    logicalOrderKey: IntegrityHash;
    idempotencyKey: IdempotencyKey;
    sequence: number;
    approvedQuantityCeiling: Quantity;
    intent?: OrderIntentPayload;
    intentHash?: IntegrityHash;
    state: OrderState;
    submissionAttempts: readonly SubmissionAttempt[];
    brokerReference?: BrokerOrderReference;
    fills: readonly NormalizedFill[];
    filledQuantity: Quantity;
    reservedCash?: Money;
    reservedDeliveryQuantity?: Quantity;
    cancellations: readonly CancellationAttemptRecord[];
    cancellationOutcomes: readonly CancellationOutcomeRecord[];
    residualWorkId?: ResidualWorkId;
    failureCode?: DomainFailureCode;
    stateVersion: number;
}>;
export declare function isTerminalOrderState(state: OrderState): boolean;
export declare function isUnresolvableTerminalState(state: OrderState): boolean;
export declare function orderAllowsCancellation(state: OrderState): boolean;
export declare function orderBlocksDependentBuys(state: OrderState): boolean;
export declare function recordIntent(snapshot: ExecutionOrderSnapshot, intent: OrderIntentPayload, intentHash: IntegrityHash, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function markOrderResidual(snapshot: ExecutionOrderSnapshot, residualWorkId: ResidualWorkId, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function startSubmission(snapshot: ExecutionOrderSnapshot, attempt: SubmissionAttempt, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function recordAcknowledged(snapshot: ExecutionOrderSnapshot, brokerReference: BrokerOrderReference, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function recordDefinitelyNotSent(snapshot: ExecutionOrderSnapshot, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function recordRetryExhausted(snapshot: ExecutionOrderSnapshot, residualWorkId: ResidualWorkId, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function recordUnknown(snapshot: ExecutionOrderSnapshot, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function recordRejected(snapshot: ExecutionOrderSnapshot, failureCode: DomainFailureCode, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function transitionToOpen(snapshot: ExecutionOrderSnapshot, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function applyFillProgress(snapshot: ExecutionOrderSnapshot, fill: NormalizedFill, newFilledQuantity: Quantity, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function applyFillReservationRelease(snapshot: ExecutionOrderSnapshot, delta: AccountingDelta): DomainResult<ExecutionOrderSnapshot>;
export declare function clearOrderReservation(snapshot: ExecutionOrderSnapshot): ExecutionOrderSnapshot;
export declare function requestCancellation(snapshot: ExecutionOrderSnapshot, cancellation: CancellationAttemptRecord, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function recordCancelled(snapshot: ExecutionOrderSnapshot, proof: Readonly<{
    reconciliationState: 'MATCHED' | 'MATCHED_WITH_ROUNDING';
    openQuantity: Quantity;
}>, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function recordCancellationOutcome(snapshot: ExecutionOrderSnapshot, outcome: CancellationOutcomeRecord, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function recordExpired(snapshot: ExecutionOrderSnapshot, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function resolveFromUnknown(snapshot: ExecutionOrderSnapshot, resolvedState: OrderState, nextVersion: number): DomainResult<ExecutionOrderSnapshot>;
export declare function requiresRetryEligible(snapshot: ExecutionOrderSnapshot, certainty: SubmissionCertainty): DomainResult<void>;
