import { type DomainFailureCode } from '../errors/failure.ts';
import { type DomainResult } from '../errors/result.ts';
import type { IntegrityHash } from '../portfolio/evidence.ts';
import type { ApprovalId, ExecutionPolicySnapshotId, ExecutionRunId, PortfolioId, RebalanceRunId, ReconciliationRunId } from '../shared/identifiers.ts';
import type { Instant } from '../shared/time.ts';
import type { PortfolioStateVersion } from '../shared/state-version.ts';
import { type ExecutionMode, type ExecutionRunState } from './contracts.ts';
export type ExecutionRunSnapshot = Readonly<{
    executionRunId: ExecutionRunId;
    portfolioId: PortfolioId;
    approvalId: ApprovalId;
    rebalanceRunId: RebalanceRunId;
    planHash: IntegrityHash;
    mode: ExecutionMode;
    state: ExecutionRunState;
    preExecutionReconciliationId: ReconciliationRunId;
    phaseReconciliationIds: readonly ReconciliationRunId[];
    policySnapshotId: ExecutionPolicySnapshotId;
    portfolioStateVersion: PortfolioStateVersion;
    createdAt: Instant;
    updatedAt: Instant;
    stateVersion: number;
    failureCode?: DomainFailureCode;
}>;
export declare function isTerminalRunState(state: ExecutionRunState): boolean;
export declare function runStateAllowsNewPlacement(state: ExecutionRunState): boolean;
export declare function transitionRunState(snapshot: ExecutionRunSnapshot, targetState: ExecutionRunState, updatedAt: Instant, nextVersion: number, reconciliationRunId?: ReconciliationRunId, failureCode?: DomainFailureCode): DomainResult<ExecutionRunSnapshot>;
export declare function advanceRunPortfolioStateVersion(snapshot: ExecutionRunSnapshot, portfolioStateVersion: PortfolioStateVersion, updatedAt: Instant, nextVersion: number): DomainResult<ExecutionRunSnapshot>;
export declare function requiresActiveRun(snapshot: ExecutionRunSnapshot): DomainResult<void>;
