import { type DomainResult } from '../errors/result.ts';
import type { IntegrityHash } from '../portfolio/evidence.ts';
import type { PortfolioId } from '../shared/identifiers.ts';
import type { ExecutionRunId } from '../shared/identifiers.ts';
import type { Money } from '../shared/money.ts';
import type { Quantity } from '../shared/quantity.ts';
import type { PortfolioStateVersion } from '../shared/state-version.ts';
import type { Instant, LocalDate } from '../shared/time.ts';
import { type ExecutionMode, type LiveEnablementSnapshot } from './contracts.ts';
import type { KillSwitchSnapshot } from './kill-switch.ts';
import type { ReconciliationRunSnapshot } from './reconciliation.ts';
import type { ApprovalDecisionSnapshot } from './approval.ts';
export type PortfolioStatus = 'ACTIVE' | 'ARCHIVED' | string;
export declare function checkPortfolioGate(portfolioStatus: PortfolioStatus): DomainResult<void>;
export declare function checkLiveEnablementGates(snapshot: LiveEnablementSnapshot, requestedMode: ExecutionMode): DomainResult<void>;
export declare function checkBrokerReadinessGate(snapshot: LiveEnablementSnapshot, requestedMode: ExecutionMode): DomainResult<void>;
export declare function checkApprovalRevalidationGate(approval: ApprovalDecisionSnapshot, executionRunId: ExecutionRunId, nowInstant: Instant, currentPlanHash: IntegrityHash, currentPortfolioVersion: PortfolioStateVersion): DomainResult<void>;
export declare function checkReconciliationGate(reconciliation: ReconciliationRunSnapshot, now: Instant, maxAgeMs: number): DomainResult<void>;
export declare function checkKillSwitchGate(globalKillSwitch: KillSwitchSnapshot | undefined, portfolioKillSwitch: KillSwitchSnapshot | undefined, portfolioId: PortfolioId): DomainResult<void>;
export type ExecutionWindowContext = Readonly<{
    executionDate: LocalDate;
    windowStart: string;
    windowEnd: string;
    timeZone: 'Asia/Kolkata';
    nowLocalDate: LocalDate;
    nowLocalTime: string;
    sameSessionAllowed: false;
}>;
export declare function checkExecutionWindowGate(window: ExecutionWindowContext): DomainResult<void>;
export type QuoteValidationContext = Readonly<{
    fetchedAt: Instant;
    staleAfter: Instant;
    nowInstant: Instant;
    maximumQuoteAgeMs: number;
    logicalOrderKey: IntegrityHash;
    proposedLimitPrice: Money;
}>;
export declare function checkQuoteGate(quote: QuoteValidationContext, approval: ApprovalDecisionSnapshot): DomainResult<void>;
export type PreTradeRiskContext = Readonly<{
    universeAllowed: boolean;
    symbolAllowed: boolean;
    productCnc: boolean;
    orderCountBelowLimit: boolean;
    dailyNotionalBelowLimit: boolean;
    positionBelowLimit: boolean;
    concentrationBelowLimit: boolean;
    turnoverBelowLimit: boolean;
    liquidityAdequate: boolean;
    drawdownBelowLimit: boolean;
    rejectionsBelowLimit: boolean;
    dataComplete: boolean;
    cashAdequate: boolean;
    noConflict: boolean;
    automationAuthorized: boolean;
}>;
export declare function checkPreTradeRiskGate(ctx: PreTradeRiskContext): DomainResult<void>;
export declare function checkSellDeliveryGate(requestedQuantity: Quantity, availableDelivery: Quantity, existingReservations: Quantity): DomainResult<void>;
export declare function checkBuyAffordabilityGate(requestedCash: Money, availableCash: Money, minimumCashBuffer: Money): DomainResult<void>;
export type AllGatesContext = Readonly<{
    portfolioStatus: PortfolioStatus;
    liveEnablement: LiveEnablementSnapshot;
    requestedMode: ExecutionMode;
    globalKillSwitch?: KillSwitchSnapshot;
    portfolioKillSwitch?: KillSwitchSnapshot;
    portfolioId: PortfolioId;
    reconciliation: ReconciliationRunSnapshot;
    reconciliationMaxAgeMs: number;
    now: Instant;
    executionWindow: ExecutionWindowContext;
    quote: QuoteValidationContext;
    approval: ApprovalDecisionSnapshot;
    executionRunId: ExecutionRunId;
    currentPlanHash: IntegrityHash;
    currentPortfolioVersion: PortfolioStateVersion;
    preTradeRisk: PreTradeRiskContext;
}>;
export declare function evaluateExecutionGates(ctx: AllGatesContext): DomainResult<void>;
