import { type DomainResult } from '../errors/result.ts';
import type { IntegrityHash } from '../portfolio/evidence.ts';
import type { BrokerAccountBindingId, InstrumentId, OrderId, PortfolioId, ReconciliationRunId, ReconciliationSnapshotId } from '../shared/identifiers.ts';
import type { Money } from '../shared/money.ts';
import type { Quantity } from '../shared/quantity.ts';
import type { Instant } from '../shared/time.ts';
import { type BrokerOrderSnapshot, type NormalizedFill, type ReconciliationReason, type ReconciliationState } from './contracts.ts';
export type DifferenceKind = 'EXTERNAL_CHANGE' | 'LOCAL_MISSING_FILL' | 'BROKER_MISSING_ORDER' | 'VALUE_MISMATCH' | 'UNKNOWN_ORDER' | 'MAPPING_BLOCKED' | 'CASH_ROUNDING';
export type DifferenceSeverity = 'INFO' | 'BLOCKING' | 'CRITICAL';
export type DifferenceResolution = 'NONE' | 'APPLY_KNOWN_FILL' | 'REQUIRES_ADJUSTMENT_APPROVAL';
export type ReconciliationDifference = Readonly<{
    differenceId: IntegrityHash;
    kind: DifferenceKind;
    severity: DifferenceSeverity;
    instrumentId?: InstrumentId;
    orderId?: OrderId;
    expected: string;
    actual: string;
    resolution: DifferenceResolution;
    absoluteMinorUnitDifference?: bigint;
    roundingEvidenceHash?: IntegrityHash;
}>;
export type ReconciledHolding = Readonly<{
    instrumentId: InstrumentId;
    totalQuantity: Quantity;
    availableDeliveryQuantity: Quantity;
    reservedQuantity: Quantity;
    averageCost?: Money;
    mappingHash: IntegrityHash;
}>;
export type ReconciliationSnapshotRecord = Readonly<{
    snapshotId: ReconciliationSnapshotId;
    source: 'LOCAL' | 'PAPER' | 'ZERODHA' | 'SHAREKHAN';
    portfolioId: PortfolioId;
    accountBindingId?: BrokerAccountBindingId;
    cash: Money;
    holdings: readonly ReconciledHolding[];
    openOrders: readonly BrokerOrderSnapshot[];
    fills: readonly NormalizedFill[];
    endpointTimes: Readonly<Record<string, Instant>>;
    cursor?: string;
    capturedAt: Instant;
    contentHash: IntegrityHash;
}>;
export type ReconciliationRunSnapshot = Readonly<{
    reconciliationRunId: ReconciliationRunId;
    portfolioId: PortfolioId;
    reason: ReconciliationReason;
    state: ReconciliationState;
    localSnapshotId: ReconciliationSnapshotId;
    externalSnapshotId?: ReconciliationSnapshotId;
    differences: readonly ReconciliationDifference[];
    startedAt: Instant;
    completedAt?: Instant;
    priorRunId?: ReconciliationRunId;
    snapshotHash: IntegrityHash;
    stateVersion: number;
}>;
export declare function isTerminalReconciliationState(state: ReconciliationState): boolean;
export declare function isReconciliationMatched(state: ReconciliationState): boolean;
export declare function transitionReconciliationState(snapshot: ReconciliationRunSnapshot, targetState: ReconciliationState, nextVersion: number, completedAt?: Instant, differences?: readonly ReconciliationDifference[], externalSnapshotId?: ReconciliationSnapshotId): DomainResult<ReconciliationRunSnapshot>;
export declare function reconciliationAllowsDependentExecution(snapshot: ReconciliationRunSnapshot, now: Instant, maxAgeMs: number): DomainResult<void>;
export declare function verifySnapshotCoherence(endpointTimes: Readonly<Record<string, Instant>>, coherentCursor?: string): DomainResult<void>;
export declare function differenceSeverityFor(kind: DifferenceKind): DifferenceSeverity;
export declare function differenceResolutionFor(kind: DifferenceKind): DifferenceResolution;
export declare function deriveReconciliationResult(differences: readonly ReconciliationDifference[]): ReconciliationState;
