import type { IdealTarget } from '../construction/ideal-target-constructor.ts';
import type { ImplementationShortfall } from '../construction/implementation-shortfall.ts';
import type { NormalizedPlanningContext, PlanningTiming } from '../construction/planning-context.ts';
import { type DomainResult } from '../errors/result.ts';
import type { IntegrityHash } from '../portfolio/evidence.ts';
import type { PortfolioId, RebalanceRunId } from '../shared/identifiers.ts';
import { type Money } from '../shared/money.ts';
import { type PlanningPhaseDuration, type SafePlanObservabilityPayload } from '../shared/safe-observability-payload-builder.ts';
import type { Instant, LocalDate } from '../shared/time.ts';
import { type Weight } from '../shared/weight.ts';
import type { ActionBuckets } from './action-buckets.ts';
import type { TurnoverBudgetEvaluation } from './cadence-and-turnover-policy.ts';
import type { ExecutableTarget } from './whole-share-greedy-allocator.ts';
export type PlanLifecycleState = 'DRAFT' | 'APPROVAL_READY' | 'SUPERSEDED' | 'INVALIDATED' | 'EXPIRED';
export type ConcentrationSnapshot = Readonly<{
    id: string;
    weight: Weight;
    limit: Weight;
}>;
export type PlanWarning = Readonly<{
    warningCode: 'BLOCKED_ACTIONS_PRESENT' | 'OPTIMIZER_FALLBACK_USED';
    severity: 'INFO' | 'WARN' | 'MANDATORY_REVIEW';
    message: string;
}>;
export type ApprovalReadySummary = Readonly<{
    currentCash: Money;
    projectedCash: Money;
    currentExposure: Weight;
    projectedExposure: Weight;
    currentSectorWeights: readonly ConcentrationSnapshot[];
    projectedSectorWeights: readonly ConcentrationSnapshot[];
    currentGroupWeights: readonly ConcentrationSnapshot[];
    projectedGroupWeights: readonly ConcentrationSnapshot[];
    totalEstimatedCosts: Money;
    totalEstimatedTaxes: Money;
    warnings: readonly PlanWarning[];
}>;
export type RebalancePlan = Readonly<{
    rebalanceRunId: RebalanceRunId;
    portfolioId: PortfolioId;
    state: PlanLifecycleState;
    planningIntent: NormalizedPlanningContext['planningIntent'];
    asOf: LocalDate;
    createdAt: Instant;
    planInputHash: IntegrityHash;
    planHash: IntegrityHash;
    context: NormalizedPlanningContext;
    idealTarget: IdealTarget;
    executableTarget: ExecutableTarget;
    implementationShortfall: ImplementationShortfall;
    actionBuckets: ActionBuckets;
    turnoverBudget: TurnoverBudgetEvaluation;
    timing: PlanningTiming;
    warnings: readonly PlanWarning[];
    summary: ApprovalReadySummary;
    observability: SafePlanObservabilityPayload;
}>;
export declare function assembleRebalancePlan(input: Readonly<{
    context: NormalizedPlanningContext;
    idealTarget: IdealTarget;
    executableTarget: ExecutableTarget;
    implementationShortfall: ImplementationShortfall;
    actionBuckets: ActionBuckets;
    turnoverBudget: TurnoverBudgetEvaluation;
    totalEstimatedCosts: Money;
    totalEstimatedTaxes: Money;
    phaseDurations: readonly PlanningPhaseDuration[];
    optimizerFallbackUsed: boolean;
}>): DomainResult<RebalancePlan>;
