export type U04RuleEvidence = Readonly<{
  ruleId: string
  description: string
  coveredIn: string
}>

function subsystem(
  prefix: string,
  descriptions: readonly string[],
  coveredIn: string,
): readonly U04RuleEvidence[] {
  return descriptions.map((description, index) => Object.freeze({
    ruleId: `${prefix}-${String(index + 1).padStart(3, '0')}`,
    description,
    coveredIn,
  }))
}

export const U04_RULE_EVIDENCE: readonly U04RuleEvidence[] = Object.freeze([
  ...subsystem('GAT', [
    'Canonical portfolio and rebalance scope is required',
    'All inputs share one portfolio scope',
    'Immutable planning lineage is complete',
    'Routine inputs use finalized EOD data',
    'Planning date follows evaluation and snapshot dates',
    'Archived portfolios cannot become approval ready',
    'Effective cost and tax versions are resolved',
    'Confirmed Asia Kolkata session metadata is required',
    'Unsafe prerequisites fail closed',
    'Ambient live state is outside the planning boundary',
    'Plan input hash exists before target construction',
    'Equivalent immutable inputs reproduce output',
  ], 'planning-gate.test.ts, rebalancing.property.test.ts'),
  ...subsystem('TGT', [
    'Candidates carry immutable evaluation lineage',
    'Mandatory exits target zero before scoring',
    'New entrants satisfy hard entry constraints',
    'Eligible incumbents may be retained',
    'Weighting uses conviction divided by volatility',
    'Volatility is positive finite and point in time',
    'Conviction remains immutable upstream input',
    'No unsafe filler positions are introduced',
    'Normalization uses exact arithmetic',
    'Regime exposure and cash buffers bind first',
    'Concentration and liquidity ceilings are hard',
    'Missing classifications block increases',
    'Every exclusion has a structured reason',
    'Ideal positions use canonical ordering',
  ], 'ideal-target.test.ts, rebalancing.property.test.ts'),
  ...subsystem('EXE', [
    'Executable quantities are whole shares',
    'Executable cash is never negative',
    'Executable positions are never short',
    'Executable output never uses leverage',
    'Sales do not exceed available delivery',
    'Initial target seed floors by finalized price',
    'Residual cash remains explicit',
    'Greedy increments preserve hard constraints',
    'Greedy ordering and ties are deterministic',
    'Allocation stops without forced investment',
    'Minimum order value applies after netting',
    'A valid no trade output is accepted',
    'Ideal deviations carry binding reasons',
    'Executable positions use canonical ordering',
    'Cash weight and notionals reconcile exactly',
  ], 'executable-target.test.ts, rebalancing.property.test.ts'),
  ...subsystem('OPT', [
    'Optimization is optional behind its port',
    'Only integer tracking and risk parity modes exist',
    'Requests include bounds objective timeout and hash',
    'Optimization stays inside hard constraints',
    'Responses include duration iterations and violations',
    'Every response is reverified',
    'All optimizer failures trigger fallback',
    'Fallback equals the deterministic greedy result',
    'Unverified optimizer output is never emitted',
    'Small problems have an exact oracle tolerance',
  ], 'optimizer.test.ts, rebalancing.property.test.ts'),
  ...subsystem('CTT', [
    'Cost schedules are versioned independently',
    'Latest effective cost schedule is selected',
    'All required cost components are included',
    'Missing cost inputs block discretionary output',
    'Live and replay cost concepts are identical',
    'Tax rules are versioned independently',
    'Latest effective tax rules are selected',
    'Tax estimation uses actual lots',
    'FIFO uses date and lot identity order',
    'HIFO uses unit cost date and lot identity order',
    'Specific selection requires instructions',
    'Hard risk may use provisional FIFO',
    'Holding period classification is effective dated',
    'After drag hurdle suppresses weak replacements',
    'Cost and tax never veto mandatory risk exits',
  ], 'cost-tax.test.ts, edge-cases.test.ts'),
  ...subsystem('CAD', [
    'Routine constituents follow assigned cadence',
    'Drift reviews follow assigned cadence',
    'Routine output uses next eligible session',
    'Manual triggers cannot bypass cadence',
    'Drift band is greater of absolute and relative',
    'Inside band holdings are skipped',
    'Preferred holds suppress only discretionary churn',
    'Hold buffers preserve healthy incumbents',
    'Replacements clear the after drag hurdle',
    'Turnover is portfolio scoped and aggregated',
    'All four approved window kinds are supported',
    'Turnover is max buy or sell over starting NAV',
    'Excess discretionary turnover is skipped',
    'Intraday and same session routine activity is forbidden',
  ], 'cadence-turnover.test.ts, rebalancing.model.test.ts'),
  ...subsystem('INT', [
    'Interim planning is denied by default',
    'Only four interim reason families are supported',
    'Exactly one reason family anchors a plan',
    'AI advisory cannot authorize interim changes',
    'Regime exceptions only reduce exposure',
    'Interim regime logic cannot authorize buys',
    'Corporate action scope is minimal',
    'Mandatory exits override discretionary preferences',
    'Interim proof carries verified attribution',
    'Unsafe interim evidence blocks planning',
  ], 'interim-authorization.test.ts, rebalancing.model.test.ts'),
  ...subsystem('PLN', [
    'Every evaluated action has one bucket',
    'Proposed orders carry exact complete values',
    'Skipped actions carry safe reasons',
    'Blocked actions identify prerequisites',
    'Every action has a semantic logical key',
    'Equivalent inputs yield equal plan hashes',
    'Equivalent plans do not duplicate orders',
    'Supersession requires material state change',
    'Plan summaries reconcile current and projected state',
    'Implementation shortfall is quantified',
    'Approval ready lineage is immutable',
    'U04 owns exactly five lifecycle states',
    'Approval readiness requires full validation',
    'Stale lineage invalidates a plan',
    'Missed execution windows expire a plan',
    'Terminal historical facts are immutable',
    'Plan explanations are safe and deterministic',
  ], 'rebalance-plan.test.ts, rebalancing.model.test.ts'),
  ...subsystem('ABU', [
    'Missing inputs fail closed',
    'Unknown values fail closed',
    'Dependency failure cannot yield unconstrained output',
    'Portfolio isolation is mandatory',
    'Identical replay cannot duplicate a basket',
    'Stale inputs are never executable',
    'Risk exits still obey executable limits',
    'Explanations never elevate unverified advisory facts',
    'Action bucket state changes require valid state changes',
    'Verifier disagreement chooses the safer state',
  ], 'architecture.test.ts, edge-cases.test.ts, rebalancing.property.test.ts'),
])
