import { get, route } from 'remix/routes'

export const routes = route({
  assets: get('/assets/*path'),
  dashboardApp: get('/dashboard-app.js'),
  dashboardCss: get('/dashboard.css'),
  etfs: get('/etfs'),
  home: '/',
  legacyDashboard: get('/nse_midcap_dashboard.html'),
  mobile: get('/mobile'),
  mobileApp: get('/mobile-app.js'),
  mobileCss: get('/mobile.css'),
  mobileIcon: get('/mobile-icon.svg'),
  mobileIcon192: get('/mobile-icon-192.png'),
  mobileIcon512: get('/mobile-icon-512.png'),
  mobileManifest: get('/mobile-manifest.webmanifest'),
  mobileServiceWorker: get('/mobile-sw.js'),
  portfolio: route('portfolio', {
    index: get('/'),
    overview: get(':portfolioId'),
    holdings: get(':portfolioId/holdings'),
    strategy: get(':portfolioId/strategy'),
    rebalance: get(':portfolioId/rebalance'),
    execution: get(':portfolioId/execution'),
    performance: get(':portfolioId/performance'),
    operations: get(':portfolioId/operations'),
  }),
  replay: get('/replay'),
  simulationEngine: get('/simulation_engine.js'),
  stocks: get('/stocks'),
  tradeRules: get('/trade_rules.js'),
})
