export const RULE_EVIDENCE = Object.freeze({
  'BR-U01-001': 'exact-values: Money exact representation',
  'BR-U01-002': 'exact-values: unsupported currency rejection',
  'BR-U01-003': 'portfolio: negative starting cash rejection',
  'BR-U01-004': 'exact-values: whole-share Quantity',
  'BR-U01-005': 'portfolio: reserved quantity guard',
  'BR-U01-006': 'exact-values: Weight boundaries',
  'BR-U01-007': 'exact-values: scale mismatch',
  'BR-U01-008': 'exact-values: non-exact conversion',
  'BR-U01-010': 'exact-values: identifier validation',
  'BR-U01-011': 'portfolio: foreign portfolio rejection',
  'BR-U01-012': 'portfolio: command context construction',
  'BR-U01-013': 'portfolio: pre-creation effective time rejection',
  'BR-U01-014': 'exact-values: Gregorian LocalDate',
  'BR-U01-015': 'architecture: no clock or identifier generation',
  'BR-U01-020': 'portfolio: initial ACTIVE version one',
  'BR-U01-021': 'portfolio: name validation',
  'BR-U01-022': 'portfolio: uniqueness proof required',
  'BR-U01-023': 'portfolio: starting cash validation',
  'BR-U01-024': 'portfolio: empty initial holdings',
  'BR-U01-025': 'portfolio: initial mode and allocation',
  'BR-U01-026': 'events: one creation event',
  'BR-U01-030': 'portfolio: closed status values',
  'BR-U01-031': 'portfolio: archive transition',
  'BR-U01-032': 'portfolio-model: archive irreversible',
  'BR-U01-033': 'portfolio: archive idempotence',
  'BR-U01-034': 'portfolio: archive retains state',
  'BR-U01-035': 'portfolio: archived mutations rejected',
  'BR-U01-036': 'architecture: archive has no external dependency',
  'BR-U01-040': 'portfolio: stale version rejection',
  'BR-U01-041': 'portfolio-property: exact version increment',
  'BR-U01-042': 'portfolio-property: failure and no-op preserve version',
  'BR-U01-043': 'events: event resulting version',
  'BR-U01-050': 'portfolio: supported modes',
  'BR-U01-051': 'portfolio: active explicit mode command',
  'BR-U01-052': 'portfolio: repeated mode no-op',
  'BR-U01-053': 'portfolio: non-execution modes need no evidence',
  'BR-U01-054': 'portfolio: approval evidence required',
  'BR-U01-055': 'portfolio: restricted evidence required',
  'BR-U01-056': 'portfolio: live evidence required',
  'BR-U01-057': 'portfolio: evidence binding and expiry',
  'BR-U01-058': 'architecture: mode grants no execution capability',
  'BR-U01-059': 'architecture: no full-auto authority',
  'BR-U01-060': 'portfolio: allocation discriminant',
  'BR-U01-061': 'portfolio: single exact full weight',
  'BR-U01-062': 'portfolio: at least two sleeves',
  'BR-U01-063': 'portfolio-property: exact sleeve total',
  'BR-U01-064': 'portfolio: unique sleeve IDs',
  'BR-U01-065': 'portfolio: unique sleeve strategies',
  'BR-U01-066': 'portfolio-property: canonical sleeve order',
  'BR-U01-067': 'portfolio: strategy evidence required',
  'BR-U01-068': 'portfolio: equivalent replacement no-op',
  'BR-U01-069': 'portfolio: future replacement retains prior event identity',
  'BR-U01-070': 'events: allocation event identities',
  'BR-U01-080': 'portfolio: holding scope',
  'BR-U01-081': 'portfolio: lot scope',
  'BR-U01-082': 'portfolio: lot sum reconciliation',
  'BR-U01-083': 'portfolio: duplicate position IDs',
  'BR-U01-084': 'portfolio-property: no short quantities',
  'BR-U01-085': 'portfolio: margin-funded quantity rejected',
  'BR-U01-086': 'portfolio-property: portfolio isolation',
  'BR-U01-090': 'events: immutable versioned facts',
  'BR-U01-091': 'events: mutation cardinality',
  'BR-U01-092': 'events: no-op cardinality',
  'BR-U01-093': 'events: aggregate binding',
  'BR-U01-094': 'architecture: safe event fields',
  'BR-U01-095': 'architecture: no publication or persistence',
  'BR-U01-100': 'portfolio: expected failure result',
  'BR-U01-101': 'portfolio-property: failure atomicity',
  'BR-U01-102': 'architecture: stable codes not messages',
  'BR-U01-103': 'events: unknown schema fails closed',
  'BR-U01-104': 'portfolio: corrupt rehydration throws invariant error',
  'BR-U01-105': 'portfolio-model: failures never become success defaults',
} satisfies Readonly<Record<`BR-U01-${string}`, string>>)
