import type { ApprovalDecisionSnapshot } from '../../domain/execution/approval.ts';
import type { NormalizedFill } from '../../domain/execution/contracts.ts';
import type { CancellationAttemptRecord, CancellationOutcomeRecord, ExecutionOrderSnapshot } from '../../domain/execution/execution-order.ts';
import type { ExecutionRunSnapshot } from '../../domain/execution/execution-run.ts';
import type { KillSwitchSnapshot } from '../../domain/execution/kill-switch.ts';
import type { ReconciliationRunSnapshot, ReconciliationSnapshotRecord } from '../../domain/execution/reconciliation.ts';
import type { AdjustmentProposal, ResidualWork } from '../../domain/execution/residual-and-adjustment.ts';
import { type PersistenceResult } from '../../infrastructure/persistence/failures.ts';
export declare const encodeExecutionApproval: (value: ApprovalDecisionSnapshot) => string;
export declare const decodeExecutionApproval: (value: unknown) => PersistenceResult<ApprovalDecisionSnapshot>;
export declare const encodeExecutionRun: (value: ExecutionRunSnapshot) => string;
export declare const decodeExecutionRun: (value: unknown) => PersistenceResult<ExecutionRunSnapshot>;
export declare const encodeExecutionOrder: (value: ExecutionOrderSnapshot) => string;
export declare const decodeExecutionOrder: (value: unknown) => PersistenceResult<ExecutionOrderSnapshot>;
export declare const encodeReconciliationRun: (value: ReconciliationRunSnapshot) => string;
export declare const decodeReconciliationRun: (value: unknown) => PersistenceResult<ReconciliationRunSnapshot>;
export declare const encodeReconciliationSnapshot: (value: ReconciliationSnapshotRecord) => string;
export declare const decodeReconciliationSnapshot: (value: unknown) => PersistenceResult<ReconciliationSnapshotRecord>;
export declare const encodeKillSwitch: (value: KillSwitchSnapshot) => string;
export declare const decodeKillSwitch: (value: unknown) => PersistenceResult<KillSwitchSnapshot>;
export declare const encodeExecutionFill: (value: NormalizedFill) => string;
export declare const decodeExecutionFill: (value: unknown) => PersistenceResult<NormalizedFill>;
export declare const encodeCancellationRequest: (value: CancellationAttemptRecord) => string;
export declare const decodeCancellationRequest: (value: unknown) => PersistenceResult<CancellationAttemptRecord>;
export declare const encodeCancellationOutcome: (value: CancellationOutcomeRecord) => string;
export declare const decodeCancellationOutcome: (value: unknown) => PersistenceResult<CancellationOutcomeRecord>;
export declare const encodeResidualWork: (value: ResidualWork) => string;
export declare const decodeResidualWork: (value: unknown) => PersistenceResult<ResidualWork>;
export declare const encodeAdjustmentProposal: (value: AdjustmentProposal) => string;
export declare const decodeAdjustmentProposal: (value: unknown) => PersistenceResult<AdjustmentProposal>;
