export declare const EXECUTION_SQL: Readonly<{
    insertApproval: "\n    INSERT INTO execution_approvals (\n      approval_id, portfolio_id, rebalance_run_id, approval_state,\n      decision_kind, idempotency_key, consumed_by_execution_run_id,\n      state_version, schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, ?)\n  ";
    selectApproval: "\n    SELECT canonical_payload FROM execution_approvals WHERE approval_id = ?\n  ";
    selectActiveApproval: "\n    SELECT canonical_payload FROM execution_approvals\n    WHERE portfolio_id = ? AND approval_state IN ('APPROVED', 'PARTIALLY_APPROVED')\n    ORDER BY state_version DESC, approval_id LIMIT 1\n  ";
    updateApproval: "\n    UPDATE execution_approvals SET\n      approval_state = ?, decision_kind = ?, consumed_by_execution_run_id = ?,\n      state_version = ?, canonical_payload = ?\n    WHERE approval_id = ? AND state_version = ?\n  ";
    insertRun: "\n    INSERT INTO execution_runs (\n      execution_run_id, portfolio_id, approval_id, run_state, mode,\n      portfolio_state_version, state_version, updated_at,\n      schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, ?)\n  ";
    selectRun: "\n    SELECT canonical_payload FROM execution_runs WHERE execution_run_id = ?\n  ";
    selectActiveRun: "\n    SELECT canonical_payload FROM execution_runs\n    WHERE portfolio_id = ?\n      AND run_state NOT IN ('BLOCKED', 'COMPLETED', 'COMPLETED_WITH_RESIDUAL', 'CANCELLED')\n    ORDER BY updated_at DESC, execution_run_id LIMIT 1\n  ";
    selectRunByApproval: "\n    SELECT canonical_payload FROM execution_runs WHERE approval_id = ?\n  ";
    selectActiveRuns: "\n    SELECT canonical_payload FROM execution_runs\n    WHERE run_state NOT IN ('BLOCKED', 'COMPLETED', 'COMPLETED_WITH_RESIDUAL', 'CANCELLED')\n    ORDER BY updated_at, execution_run_id\n  ";
    updateRun: "\n    UPDATE execution_runs SET\n      run_state = ?, portfolio_state_version = ?, state_version = ?,\n      updated_at = ?, canonical_payload = ?\n    WHERE execution_run_id = ? AND state_version = ?\n  ";
    insertOrder: "\n    INSERT INTO execution_orders (\n      order_id, execution_run_id, portfolio_id, instrument_id, side,\n      order_state, logical_order_key, idempotency_key, order_sequence,\n      approved_quantity_shares, filled_quantity_shares,\n      broker_order_reference_id, state_version, schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)\n  ";
    selectOrder: "\n    SELECT canonical_payload FROM execution_orders WHERE order_id = ?\n  ";
    selectOrdersByRun: "\n    SELECT canonical_payload FROM execution_orders\n    WHERE execution_run_id = ? ORDER BY order_sequence, order_id\n  ";
    selectOrderByBrokerReference: "\n    SELECT canonical_payload FROM execution_orders\n    WHERE portfolio_id = ? AND broker_order_reference_id = ?\n  ";
    selectGlobalCancellableOrders: "\n    SELECT canonical_payload FROM execution_orders\n    WHERE order_state IN ('ACKNOWLEDGED', 'OPEN', 'PARTIALLY_FILLED')\n    ORDER BY portfolio_id, execution_run_id, order_sequence, order_id\n  ";
    selectPortfolioCancellableOrders: "\n    SELECT canonical_payload FROM execution_orders\n    WHERE portfolio_id = ?\n      AND order_state IN ('ACKNOWLEDGED', 'OPEN', 'PARTIALLY_FILLED')\n    ORDER BY execution_run_id, order_sequence, order_id\n  ";
    updateOrder: "\n    UPDATE execution_orders SET\n      order_state = ?, filled_quantity_shares = ?,\n      broker_order_reference_id = ?, state_version = ?, canonical_payload = ?\n    WHERE order_id = ? AND state_version = ?\n  ";
    insertReconciliationRun: "\n    INSERT INTO reconciliation_runs (\n      reconciliation_run_id, portfolio_id, reconciliation_state, reason,\n      started_at, completed_at, prior_run_id, state_version,\n      schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, ?)\n  ";
    selectReconciliationRun: "\n    SELECT canonical_payload FROM reconciliation_runs WHERE reconciliation_run_id = ?\n  ";
    selectLatestReconciliationRun: "\n    SELECT canonical_payload FROM reconciliation_runs\n    WHERE portfolio_id = ?\n    ORDER BY started_at DESC, reconciliation_run_id DESC LIMIT 1\n  ";
    updateReconciliationRun: "\n    UPDATE reconciliation_runs SET\n      reconciliation_state = ?, completed_at = ?, state_version = ?,\n      canonical_payload = ?\n    WHERE reconciliation_run_id = ? AND state_version = ?\n  ";
    insertReconciliationSnapshot: "\n    INSERT INTO reconciliation_snapshots (\n      snapshot_id, portfolio_id, source, content_hash, captured_at,\n      schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, 1, ?)\n  ";
    selectReconciliationSnapshot: "\n    SELECT canonical_payload FROM reconciliation_snapshots WHERE snapshot_id = ?\n  ";
    insertKillSwitch: "\n    INSERT INTO execution_kill_switches (\n      kill_switch_id, scope_kind, portfolio_id, switch_state,\n      state_version, schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, 1, ?)\n  ";
    selectKillSwitch: "\n    SELECT canonical_payload FROM execution_kill_switches WHERE kill_switch_id = ?\n  ";
    selectGlobalKillSwitch: "\n    SELECT canonical_payload FROM execution_kill_switches\n    WHERE scope_kind = 'GLOBAL' LIMIT 1\n  ";
    selectPortfolioKillSwitch: "\n    SELECT canonical_payload FROM execution_kill_switches\n    WHERE scope_kind = 'PORTFOLIO' AND portfolio_id = ? LIMIT 1\n  ";
    updateKillSwitch: "\n    UPDATE execution_kill_switches SET\n      switch_state = ?, state_version = ?, canonical_payload = ?\n    WHERE kill_switch_id = ? AND state_version = ?\n  ";
    insertFill: "\n    INSERT INTO execution_fills (\n      fill_id, order_id, execution_run_id, portfolio_id, instrument_id,\n      side, quantity_shares, price_minor_units, content_hash, trade_time,\n      schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)\n  ";
    selectFill: "\n    SELECT canonical_payload FROM execution_fills WHERE fill_id = ?\n  ";
    insertCancellationRequest: "\n    INSERT INTO execution_cancellation_requests (\n      cancellation_id, order_id, portfolio_id, idempotency_key,\n      requested_at, schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, 1, ?)\n  ";
    selectCancellationRequest: "\n    SELECT canonical_payload FROM execution_cancellation_requests\n    WHERE cancellation_id = ?\n  ";
    selectCancellationByIdempotency: "\n    SELECT canonical_payload FROM execution_cancellation_requests\n    WHERE order_id = ? AND idempotency_key = ?\n  ";
    insertCancellationOutcome: "\n    INSERT INTO execution_cancellation_outcomes (\n      cancellation_id, outcome, completed_at, schema_version, canonical_payload\n    ) VALUES (?, ?, ?, 1, ?)\n  ";
    selectCancellationOutcome: "\n    SELECT canonical_payload FROM execution_cancellation_outcomes\n    WHERE cancellation_id = ?\n  ";
    insertResidualWork: "\n    INSERT INTO execution_residual_work (\n      residual_work_id, execution_run_id, order_id, portfolio_id,\n      remaining_quantity_shares, reason, created_at,\n      schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?)\n  ";
    selectResidualWork: "\n    SELECT canonical_payload FROM execution_residual_work WHERE residual_work_id = ?\n  ";
    insertAdjustmentProposal: "\n    INSERT INTO execution_adjustment_proposals (\n      adjustment_proposal_id, reconciliation_run_id, portfolio_id,\n      proposal_state, content_hash, state_version,\n      schema_version, canonical_payload\n    ) VALUES (?, ?, ?, ?, ?, ?, 1, ?)\n  ";
    selectAdjustmentProposal: "\n    SELECT canonical_payload FROM execution_adjustment_proposals\n    WHERE adjustment_proposal_id = ?\n  ";
    updateAdjustmentProposal: "\n    UPDATE execution_adjustment_proposals SET\n      proposal_state = ?, state_version = ?, canonical_payload = ?\n    WHERE adjustment_proposal_id = ? AND state_version = ?\n  ";
    selectPortfolioStatusVersion: "\n    SELECT status, state_version FROM portfolios WHERE portfolio_id = ?\n  ";
    selectPortfolioByReconciliationRun: "\n    SELECT portfolio_id FROM reconciliation_runs WHERE reconciliation_run_id = ?\n  ";
    selectPortfolioByOrder: "\n    SELECT portfolio_id FROM execution_orders WHERE order_id = ?\n  ";
    selectResetPortfolioVersions: "\n    SELECT portfolio_id, state_version FROM portfolios\n    WHERE portfolio_id IN (\n      SELECT portfolio_id FROM execution_orders\n      WHERE order_state IN (\n        'SUBMISSION_IN_FLIGHT', 'ACKNOWLEDGED', 'OPEN',\n        'PARTIALLY_FILLED', 'UNKNOWN', 'CANCEL_PENDING'\n      )\n    )\n    ORDER BY portfolio_id\n  ";
}>;
